# Form implementation generated from reading ui file 'ble_demo_ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BLE_DEMO(object):
    def setupUi(self, BLE_DEMO):
        BLE_DEMO.setObjectName("BLE_DEMO")
        BLE_DEMO.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=BLE_DEMO)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_serach = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_serach.setGeometry(QtCore.QRect(160, 80, 75, 24))
        self.btn_serach.setObjectName("btn_serach")
        self.cb_device = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cb_device.setGeometry(QtCore.QRect(280, 80, 341, 22))
        self.cb_device.setObjectName("cb_device")
        self.btn_con = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_con.setGeometry(QtCore.QRect(160, 160, 75, 24))
        self.btn_con.setObjectName("btn_con")
        self.et_data = PlainTextEdit(parent=self.centralwidget)
        self.et_data.setGeometry(QtCore.QRect(160, 200, 461, 192))
        self.et_data.setObjectName("et_data")
        self.btn_discon = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_discon.setGeometry(QtCore.QRect(460, 160, 75, 24))
        self.btn_discon.setObjectName("btn_discon")
        self.btn_clear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(550, 160, 75, 24))
        self.btn_clear.setObjectName("btn_clear")
        self.btn_start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(260, 160, 75, 24))
        self.btn_start.setObjectName("btn_start")
        self.btn_pause = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_pause.setGeometry(QtCore.QRect(360, 160, 75, 24))
        self.btn_pause.setObjectName("btn_pause")
        BLE_DEMO.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=BLE_DEMO)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        BLE_DEMO.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=BLE_DEMO)
        self.statusbar.setObjectName("statusbar")
        BLE_DEMO.setStatusBar(self.statusbar)

        self.retranslateUi(BLE_DEMO)
        QtCore.QMetaObject.connectSlotsByName(BLE_DEMO)

    def retranslateUi(self, BLE_DEMO):
        _translate = QtCore.QCoreApplication.translate
        BLE_DEMO.setWindowTitle(_translate("BLE_DEMO", "MainWindow"))
        self.btn_serach.setText(_translate("BLE_DEMO", "搜索"))
        self.btn_con.setText(_translate("BLE_DEMO", "连接"))
        self.btn_discon.setText(_translate("BLE_DEMO", "断开"))
        self.btn_clear.setText(_translate("BLE_DEMO", "清空"))
        self.btn_start.setText(_translate("BLE_DEMO", "开始"))
        self.btn_pause.setText(_translate("BLE_DEMO", "暂停"))
from qfluentwidgets import PlainTextEdit
